/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sharpie.grindsim.sim;

import sharpie.grindsim.config.SimConfig;
import sharpie.grindsim.results.SimulatorResults;

public class GrindSimulator {


    public SimulatorResults runSim(SimConfig config) {

        config.resetStats();

        while (config.shouldKeepRunning()) {

            config.runTrial();
        }

        return config.getResults();
    }
}
