/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sharpie.sim;

public class GrindSimulator {


    public SimulatorResults runSim(SimConfig config) {

        config.resetStats();

        while (config.shouldKeepRunning()) {

            config.runTrial();
        }

        return config.getResults();
    }

    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
